### PR TITLE
Fix uclient certificate loading bug

### LINKED ISSUE #376: turnutils_uclient not supporting TLS 1.2?
Hi,
It seems if we disable tls1.0 and tls1.1 on turnserver config, the uclient will not able to connect the server via TLS.

Is this something in backlog or no one ever brought up? I might be able to make a PR if no one is planning work on it

Thanks,

### PR DESCRIPTION
**Pull request by eakraly**
When using `turnutils_uclient` with `-S` flag (TLS or DTLS) it is not required to load certificates. Only load certificates when corresponding flags are provided

Fixes #376 which prevented using `turnutils_uclient` for testing TLS/DTLS connections

Test plan:
- Run local turnserver with certificates `./bin/turnserver --cert ./bin/public.pem --pkey ./bin/private.key --use-auth-secret  --static-auth-secret=secret --realm=north.gov --allow-loopback-peers --no-cli --verbose`
- Run fixed uclient without TLS/DTLS`./bin/turnutils_uclient -e 127.0.0.1 -X -g -u user -W secret 127.0.0.1` and get success result (just to make sure non-secure still works)
- Run fixed uclient with TLS `./bin/turnutils_uclient -e 127.0.0.1 -X -g -u user -W secret -t -S 127.0.0.1` and get success result
- Run fixed uclient with DTLS `./bin/turnutils_uclient -e 127.0.0.1 -X -g -u user -W secret -S 127.0.0.1` and get success result
- Run unpatched uclient with TLS `./bin/turnutils_uclient -e 127.0.0.1 -X -g -u user -W secret -t -S 127.0.0.1` - error about missing certificate files

### CODE REVIEW

File: src/apps/uclient/mainuclient.c [hunk 1]
```diff
@@ -520,48 +520,59 @@ int main(int argc, char **argv)
...
 				SSL_CTX_set_verify_depth(root_tls_ctx[sslind], 9);
-			} else {
+			} 
+			else 
+			{
 				SSL_CTX_set_verify(root_tls_ctx[sslind], SSL_VERIFY_NONE, NULL );
 			}
-
-			if(!use_tcp)
-				SSL_CTX_set_read_ahead(root_tls_ctx[sslind], 1);
```
Comment (eakraly) [inline src/apps/uclient/mainuclient.c:564]: `SSL_CTX_set_read_ahead` for DTLS is no-op, see https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_read_ahead.html

File: src/apps/uclient/mainuclient.c [hunk 2]
```diff
@@ -520,48 +520,59 @@ int main(int argc, char **argv)
...
+				exit(-1);
 			}
 
-			if (ca_cert_file[0]) {
+			if (use_ca_cert) 
+			{
 				if (!SSL_CTX_load_verify_locations(root_tls_ctx[sslind], ca_cert_file, NULL )) {
 					TURN_LOG_FUNC(TURN_LOG_LEVEL_ERROR,
-							"ERROR: cannot load CA from file: %s\n",
+							"ERROR: cannot load CA from file\n",
```
Comment (eakraly) [inline src/apps/uclient/mainuclient.c:561]: Changing for consistency - other log lines did not print file name (and it is redundant as it explains exactly what file failed to load)

**Review by ggarber — APPROVED** [review]
